variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - test
  - build
  - update-chart

sonarqube-backend-sast:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - cd backend
    - >
      sonar-scanner
      -Dsonar.sources=. 
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN}
      -Dsonar.projectName="Dmitriy_Kuropatko_momostore_b"
  when: manual    

spotbugs-sast:
  stage: test
  script:
    - cd frontend

go-test:
  stage: test
  image: golang:latest
  script:
    - cd backend
    - go test -v ./...
  allow_failure: true

build-backend-code-job: 
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  # переменные CI_REGISTRY_USER, CI_REGISTRY_PASSWORD, CI_REGISTRY генерятся Гитлабом, их задавать не надо
  script:
    - echo "test"
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/backend:$CI_COMMIT_SHA"
      --build-arg VERSION=$VERSION
      --cache=true      

# release:
#   variables:
#     GIT_STRATEGY: none
#   image:
#     name: gcr.io/go-containerregistry/crane:debug
#     entrypoint: [ "" ]
#   cache: [ ]
#   stage: release
#   before_script:
#     - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   script:
#     - crane tag $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_SHA $VERSION
