apiVersion: v2
appVersion: 1.0.1635235
dependencies:
- name: backend
  repository: ""
  version: 1.0.0
- name: frontend
  repository: ""
  version: 1.0.1
description: momo-store Helm Chart
name: momo-store
type: application
version: 1.0.1635235
