# values.yaml !!!
backend: # Это имя чарта из dependencies
  # Вместо latest правильнее использовать версию .Chart.AppVersion в шаблоне
  image:
    repository: gitlab.praktikum-services.ru:5050/std-ext-008-12/momostore/
    tag: latest
    pullPolicy: IfNotPresent

  spec:
      replicas: "1"
      revisionHistoryLimit: "15"
  strategy:
    rollingUpdate:
      maxUnavailable: "20%"
      maxSurge: "1"
  ports:
      containerPort: "8081"
#  livenessProbe:
#    initialDelaySeconds: "180"
#    periodSeconds: "31"
#    timeoutSeconds: "1"
#    failureThreshold: "7"

frontend:
  image:
    repository: gitlab.praktikum-services.ru:5050/std-ext-008-12/momostore/
    tag: latest
    pullPolicy: IfNotPresent 

  spec: 
      replicas: "1" 
      revisionHistoryLimit: "15"
  ports:
      containerPort: "80"
      nodePort: "30081"
  fqdn: momo.kuropatko.ru
  annotations:
    subnets: enphj2i0ko9gobd7g7vq
    securityGroups: enp7urf4ha7i7db8q674
    groupName: "for-k8s-nodegroup"