---
apiVersion: v1
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewogICAgImF1dGhzIjogewogICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICJhdXRoIjogIlRXOXRiMU4wY205eVpUcEJlVXRUY0VjeFZuaDRaVzlYVWtST1h6aFRTdz09IgogICAgICAgIH0KICAgIH0KfSA=
type: kubernetes.io/dockerconfigjson